#!/usr/bin/env bash
# deploy/setup.sh — One-time setup for Ledger on Tailscale + Docker
#
# What this script does:
#   1. Verifies prerequisites (docker, tailscale)
#   2. Detects your Tailscale IP (100.x.x.x)
#   3. Prompts for credentials and generates a secure NEXTAUTH_SECRET
#   4. Writes a .env file in the project root
#   5. Builds the Docker image
#   6. Installs and enables a systemd service so the container starts on boot
#
# Usage (run from the repo root):
#   chmod +x deploy/setup.sh && sudo deploy/setup.sh
#
# To re-run after changing credentials, just run the script again — it is
# idempotent and will overwrite the existing .env and service file.

set -euo pipefail

# ── Helpers ──────────────────────────────────────────────────────────────────

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

info()    { echo -e "${CYAN}[ledger]${NC} $*"; }
success() { echo -e "${GREEN}[ledger]${NC} $*"; }
warn()    { echo -e "${YELLOW}[ledger]${NC} $*"; }
die()     { echo -e "${RED}[ledger] ERROR:${NC} $*" >&2; exit 1; }

require_cmd() { command -v "$1" &>/dev/null || die "'$1' is not installed. $2"; }

# ── Privilege check ───────────────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
  die "This script must be run as root (sudo deploy/setup.sh)."
fi

# ── Locate project root ───────────────────────────────────────────────────────

# Always resolve relative to this script's location so the service file and
# .env end up in the right place regardless of where the user calls from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

info "Project directory: $PROJECT_DIR"

# ── Prerequisites ─────────────────────────────────────────────────────────────

require_cmd docker   "Install Docker: https://docs.docker.com/engine/install/"
require_cmd tailscale "Install Tailscale: https://tailscale.com/download"
require_cmd openssl  "Install openssl (usually pre-installed)."

# Ensure Docker Compose v2 plugin is available.
docker compose version &>/dev/null || die "Docker Compose plugin not found. Install it alongside Docker Engine."

# Ensure Tailscale is connected.
TAILSCALE_STATUS=$(tailscale status --json 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('BackendState',''))" 2>/dev/null || true)
[[ "$TAILSCALE_STATUS" == "Running" ]] || die "Tailscale is not connected. Run 'sudo tailscale up' first."

# ── Detect Tailscale IP ───────────────────────────────────────────────────────

TAILSCALE_IP=$(tailscale ip -4 2>/dev/null | head -n1)
[[ -n "$TAILSCALE_IP" ]] || die "Could not determine Tailscale IPv4 address."

success "Tailscale IP detected: $TAILSCALE_IP"

# ── Gather credentials ────────────────────────────────────────────────────────

echo ""
info "Enter your Ledger credentials (press Enter to accept defaults)."
echo ""

read -rp "  Admin email   [admin@ledger.local]: " ADMIN_EMAIL
ADMIN_EMAIL="${ADMIN_EMAIL:-admin@ledger.local}"

while true; do
  read -rsp "  Admin password (min 8 chars): " ADMIN_PASSWORD
  echo ""
  [[ ${#ADMIN_PASSWORD} -ge 8 ]] && break
  warn "Password must be at least 8 characters. Try again."
done

# ── Generate NEXTAUTH_SECRET ──────────────────────────────────────────────────

NEXTAUTH_SECRET=$(openssl rand -base64 32)
success "Generated NEXTAUTH_SECRET."

# ── Write .env ────────────────────────────────────────────────────────────────

ENV_FILE="$PROJECT_DIR/.env"

cat > "$ENV_FILE" <<EOF
# Generated by deploy/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file — it contains secrets.

# ── Tailscale ────────────────────────────────────────────────────────────────
TAILSCALE_IP=${TAILSCALE_IP}

# ── Database ─────────────────────────────────────────────────────────────────
DATABASE_URL=/data/ledger.db

# ── NextAuth ──────────────────────────────────────────────────────────────────
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=http://${TAILSCALE_IP}:3000

# ── Admin credentials ─────────────────────────────────────────────────────────
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
EOF

chmod 600 "$ENV_FILE"
success ".env written to $ENV_FILE"

# ── Build Docker image ────────────────────────────────────────────────────────

echo ""
info "Building Docker image (this may take a few minutes on first run)…"
docker compose -f "$PROJECT_DIR/docker-compose.yml" --env-file "$ENV_FILE" build

success "Docker image built."

# ── Install systemd service ───────────────────────────────────────────────────

SERVICE_NAME="ledger"
SERVICE_SRC="$SCRIPT_DIR/ledger.service"
SERVICE_DEST="/etc/systemd/system/${SERVICE_NAME}.service"

# Substitute the actual project path into the service file.
sed "s|LEDGER_DIR_PLACEHOLDER|${PROJECT_DIR}|g" "$SERVICE_SRC" > "$SERVICE_DEST"
chmod 644 "$SERVICE_DEST"

systemctl daemon-reload
systemctl enable "$SERVICE_NAME"

echo ""
info "Starting Ledger…"
systemctl start "$SERVICE_NAME"

# ── Done ──────────────────────────────────────────────────────────────────────

echo ""
success "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
success " Ledger is running!"
success ""
success "   URL : http://${TAILSCALE_IP}:3000"
success "   User: ${ADMIN_EMAIL}"
success ""
success " The container will start automatically on every boot."
success " To check status : sudo systemctl status ledger"
success " To view logs    : docker compose -C ${PROJECT_DIR} logs -f"
success " To stop         : sudo systemctl stop ledger"
success " To rebuild      : docker compose -C ${PROJECT_DIR} build"
success "                   then: sudo systemctl restart ledger"
success "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
